spring.application.name=EurekaServer

server.port=${PORT:8761}

# Eureka Server should NOT register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Faster startup on cloud platforms
eureka.server.wait-time-in-ms-when-sync-empty=0

# Render hostname
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:nookeureka-server.onrender.com}
eureka.instance.prefer-ip-address=false