spring.application.name=EurekaServer
server.port=${PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

eureka.server.peer-eureka-nodes-update-interval-ms=60000
eureka.client.service-url.defaultZone=https://nookeureka-server.onrender.com/eureka/

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:nookeureka-server.onrender.com}
eureka.instance.prefer-ip-address=false