#spring.application.name=EurekaServer
#server.port=8761
#
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.server.wait-time-in-ms-when-sync-empty=0
#
#eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
#eureka.instance.prefer-ip-address=false


spring.application.name=EurekaServer

server.port=${PORT:8761}

# IMPORTANT
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# REMOVE localhost replication
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:https://nookeureka-server.onrender.com/eureka/}

eureka.server.wait-time-in-ms-when-sync-empty=0

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:nookeureka-server.onrender.com}
eureka.instance.prefer-ip-address=false